Repository KCC-Team/Spring-Miniproject, pull requests merged in 2024-09, with the labels that each got.

#47 모임의 총 게시글 및 총 갯수 구하는 로직 구현
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/post/repository/mapper/PostMapper.java
  src/main/java/com/kcc/springmini/domain/post/service/PostService.java
  src/main/java/com/kcc/springmini/domain/post/service/PostServiceImpl.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/PostMapper.xml
Labels: feature

#42 [#39] 마이페이지 회원수정, 회원탈퇴 기능 구현
  src/main/webapp/resources/css/meetupRegister.css
Labels: bug

#50 모임 컨트롤러 및 뷰 생성(게시글, 회원)
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/css/meetupDetail.css
Labels: feature

#52 jsp_jstl 의존성 추가
  bin/pom.xml
Labels: setting

#54 [#34] 모임 일정 참가 신청 api 연동
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: feature, refactor

#56 refactor: 모임 상세 페이지 조회 개선 (#noissue)
  pom.xml
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/post/service/PostService.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/resources/common/header.jsp
Labels: fix

#57 [#53] 메인페이지 모임 목록 조회
  src/main/java/com/kcc/springmini/MainController.java
  src/main/webapp/WEB-INF/views/member/loginForm.jsp
Labels: bug

#58 [#53] 메인페이지 모임 목록 조회
  src/main/java/com/kcc/springmini/MainController.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/Criteria.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/PageDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/vo/MeetUpVO.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/meetupRegister.css
  src/main/webapp/resources/js/main.js
Labels: feature

#60 모임 게시글 페이징 구현
  pom.xml
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
Labels: fix

#61 모임 게시글 페이징 구현
  pom.xml
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: setting

#63 [#34] 모임 일정 기능 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleRequestDto.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix, feature

#65 Setting/pom header
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/post/repository/mapper/PostMapper.java
  src/main/java/com/kcc/springmini/domain/post/service/PostService.java
  src/main/java/com/kcc/springmini/domain/post/service/PostServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/PostMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/postDetail.jsp
Labels: bug

#66 [#34] 모임 일정 단일 조회 로직 오류 개선
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/PageResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleListResponseDto.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix

#68 [#62] 파일 경로 수정 및 리팩토링
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/webapp/WEB-INF/views/member/memberModify.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/resources/js/joinForm.js
Labels: refactor

#72 [#71] 모임 참가 버튼 로직 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
Labels: feature

#74 [#73] MemerVO 수정
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/data.sql
Labels: refactor

#75 모임 생성 로직 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupRegister.jsp
Labels: feature

#78 [#77] principalDetails 미인식 문제 개선
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/reply/controller/ReplyController.java
  src/main/java/com/kcc/springmini/global/auth/PrincipalDetail.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
Labels: fix, docs

#79 [#noissue] fix: 코드 에러 개선
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/reply/controller/ReplyController.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
Labels: fix

#81 [#80] 더미 사용자 계정 추가
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/application.yml
Labels: feature

#83 [#80] 회원 더미데이터 수정
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: refactor

#84 [#71] 모임 참가 로직 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/exception/AlreadyExistException.java
  src/main/java/com/kcc/springmini/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/NotFoundToErrorException.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/WEB-INF/views/404.jsp
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix, feature

#85 Feat/71 meetup insert
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/post/model/vo/PostVO.java
  src/main/java/com/kcc/springmini/global/config/dummy
  src/main/resources/mapper/MeetUpMapper.xml
Labels: refactor

#86 [#82] 로그인 및 모임 소속 사용자로 제한한 댓글 추가 로직 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/reply/controller/ReplyController.java
  src/main/java/com/kcc/springmini/domain/reply/model/dto/ReplyCreateRequestDto.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
Labels: fix

#88 [#73] 마이페이지 모임 목록 조회
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/resources/css/mypage.css
Labels: feature

#90 답변 테이블 추가 및 소속회원 등급속성추가
  src/main/resources/data.sql
Labels: fix

#94 [#noissue] 동시성 테스트를 위한 더미 데이터 추가
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
Labels: refactor

#98 [#97] 모임 일정 생성 뷰 개선
  src/main/java/com/kcc/springmini/domain/common/config/SchedulerConfig.java
  src/main/java/com/kcc/springmini/domain/common/service/SchedulerService.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/resources/js/meetupDetail.js
Labels: refactor

#99 [#93] 회원가입 검증
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/global/exception/ControllerlExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/RestControllerExceptionHandler.java
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
  src/main/webapp/WEB-INF/views/member/memberModify.jsp
  src/main/webapp/resources/css/joinForm.css
  src/main/webapp/resources/js/joinForm.js
Labels: refactor

#101 [#97] 테스트 환경 구축 및 AOP 로직 구현
  pom.xml
  src/main/java/com/kcc/springmini/domain/common/config/AopConfig.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/aop/LoginAspect.java
  src/main/java/com/kcc/springmini/global/aop/LoginValid.java
  src/main/java/com/kcc/springmini/global/aop/dummy
  src/main/java/com/kcc/springmini/global/exception/ForbiddenException.java
  src/main/java/com/kcc/springmini/global/exception/RestControllerExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/UnAuthorizedException.java
  src/main/resources/application.yml
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/member/loginForm.jsp
  src/main/webapp/resources/js/meetupRegister.js
  src/test/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryTest.java
Labels: feature, refactor

#102 [#noissue] 테스트 환경 설정
  src/main/java/com/kcc/springmini/global/exception/RestControllerExceptionHandler.java
  src/main/java/com/kcc/springmini/global/init/init.java
Labels: feature, test

#103 [#95] 회원 승인 로직 추가
  src/main/java/com/kcc/springmini/domain/meetup/controller/AnswerDto.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/vo/Question.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberQAResponseDto.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/QuestionAnswer.java
  src/main/resources/data.sql
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
Labels: fix, feature

#104 [#noissue] 컨트롤러 잘못된 이슈 해결
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
Labels: fix

#105 [#95] 회원 승인 로직 추가
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberApproveRequestDto.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberQAResponseDto.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberRequestDto.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/QuestionAnswer.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/data.sql
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: feature

#107 [#100] 화면 디자인 수정
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/meetupRegister.jsp
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
  src/main/webapp/WEB-INF/views/member/memberModify.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/css/joinForm.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/css/meetupRegister.css
  src/main/webapp/resources/css/memberModify.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/js/joinForm.js
  src/main/webapp/resources/js/main.js
  src/main/webapp/resources/js/meetupDetail.js
  src/main/webapp/resources/js/meetupRegister.js
Labels: refactor

#109 [#108] 게시글 작성
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/post/model/vo/BoardVO.java
  src/main/java/com/kcc/springmini/domain/post/repository/mapper/PostMapper.java
  src/main/java/com/kcc/springmini/domain/post/service/PostService.java
  src/main/java/com/kcc/springmini/domain/post/service/PostServiceImpl.java
  src/main/resources/mapper/PostMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
Labels: feature

#111 Feat/110 schedule add logic
  pom.xml
  src/main/java/com/kcc/springmini/domain/common/config/AwsS3Config.java
  src/main/java/com/kcc/springmini/domain/common/dummy/DummyController.java
  src/main/java/com/kcc/springmini/domain/common/dummy/DummyService.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/aop/LoginAspect.java
  src/main/java/com/kcc/springmini/global/aop/LoginValid.java
  src/main/java/com/kcc/springmini/global/exception/ControllerlExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/RestControllerExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
Labels: feature, refactor

#113 [#112] 시큐리티 수정 및 디자인 수정
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/postDetail.jsp
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
Labels: refactor

#115 모임 가입 질문 여러개 생성 시 서버단 적용
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/reply/repository/ReplyRepository.java
  src/main/java/com/kcc/springmini/domain/reply/repository/ReplyRepositoryImpl.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/mapper/PostMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/meetupRegister.jsp
  src/main/webapp/resources/js/meetupRegister.js
  src/test/java/com/kcc/springmini/domain/reply/repository/ReplyRepositoryTest.java
  src/test/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryTest.java
Labels: fix

#116 [#100] 모임 일정 추가 로직 구현
  src/main/java/com/kcc/springmini/domain/common/config/AwsS3Config.java
  src/main/java/com/kcc/springmini/domain/common/config/EnvVariableProperties.java
  src/main/java/com/kcc/springmini/domain/common/config/SchedulerConfig.java
  src/main/java/com/kcc/springmini/domain/common/mapper/FileMapper.java
  src/main/java/com/kcc/springmini/domain/common/model/FileResponseDto.java
  src/main/java/com/kcc/springmini/domain/common/model/FileStatus.java
  src/main/java/com/kcc/springmini/domain/common/service/FileService.java
  src/main/java/com/kcc/springmini/domain/common/utils/AwsS3Utils.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/AnswerDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/vo/MeetUpVO.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/post/mapper/PostMapper.java
  src/main/java/com/kcc/springmini/domain/post/model/vo/PostVO.java
  src/main/java/com/kcc/springmini/domain/post/repository/PostRepository.java
  src/main/java/com/kcc/springmini/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/post/service/PostServiceImpl.java
  src/main/java/com/kcc/springmini/domain/reply/mapper/ReplyMapper.java
  src/main/java/com/kcc/springmini/domain/reply/repository/ReplyRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/reply/repository/mapper/ReplyMapper.java
  src/main/java/com/kcc/springmini/domain/reply/service/ReplyServiceImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/auth/PrincipalDetailService.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/postDetail.jsp
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
  src/test/java/com/kcc/springmini/domain/reply/repository/ReplyRepositoryTest.java
  src/test/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryTest.java
Labels: feature, refactor

#117 회원가입 폼 수정
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
  src/main/webapp/resources/css/joinForm.css
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
Labels: refactor

#119 [#noissue] 충돌 해결
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/exception/ControllerlExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix

#122 회원가입 이미지 업로드 추가
  src/main/java/com/kcc/springmini/MainController.java
  src/main/java/com/kcc/springmini/domain/common/mapper/FileMapper.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
Labels: feature

#124 댓글 수정 및 권한없는 회원 게시글 상세 접근 제한
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/reply/controller/ReplyController.java
  src/main/java/com/kcc/springmini/domain/reply/mapper/ReplyMapper.java
  src/main/java/com/kcc/springmini/domain/reply/model/dto/ReplyRequestDto.java
  src/main/java/com/kcc/springmini/domain/reply/model/dto/ReplyUpdateRequestDto.java
  src/main/java/com/kcc/springmini/domain/reply/service/ReplyService.java
  src/main/java/com/kcc/springmini/domain/reply/service/ReplyServiceImpl.java
  src/main/resources/mapper/ReplyMapper.xml
  src/main/webapp/WEB-INF/views/meetup/alert.jsp
  src/main/webapp/WEB-INF/views/meetup/postDetail.jsp
Labels: feature

#125 [#noissue] 오류 개선
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix

#127 마이페이지 / 디자인 수정
  src/main/java/com/kcc/springmini/global/exception/ControllerExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/ControllerlExceptionHandler.java
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/resources/css/meetupDetail.css
Labels: refactor

#128 [#110] schedule 검증 사항 개선
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/resources/js/meetupDetail.js
Labels: refactor

#132 마이페이지 / 디자인 수정
  src/main/java/com/kcc/springmini/global/exception/ControllerExceptionHandler.java
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/css/joinForm.css
  src/main/webapp/resources/css/meetupDetail.css
  src/main/webapp/resources/css/memberModify.css
Labels: refactor

#133 [#noissue] 예외 핸들러 통일
  pom.xml
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/exception/ControllerExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/RestControllerExceptionHandler.java
  src/main/java/com/kcc/springmini/global/init/init.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: fix, refactor

#135 파일 리팩토링
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
Labels: refactor

#137 댓글 수정 및 상세 접근 제한 및 최종 병합
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/reply/controller/ReplyController.java
  src/main/java/com/kcc/springmini/domain/reply/model/Reply.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/main/resources/mapper/MeetUpMapper.xml
  src/main/resources/mapper/PostMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/WEB-INF/views/meetup/postDetail.jsp
Labels: feature
