Repository KCC-Team/Spring-Miniproject, pull requests merged in 2024-08, with the labels that each got.

#3 파일 합침
  aa
  bb
Labels: feature

#12 [#7] 공통 header, footer 구현
  src/main/webapp/WEB-INF/views/common/common.css
  src/main/webapp/WEB-INF/views/common/footer.html
  src/main/webapp/WEB-INF/views/main.css
  src/main/webapp/WEB-INF/views/main.html
Labels: feature

#14 create meetUpDetail
  src/main/webapp/WEB-INF/views/common/common.css
  src/main/webapp/WEB-INF/views/common/common.js
  src/main/webapp/WEB-INF/views/main.css
  src/main/webapp/WEB-INF/views/meetup/css/meetUpDetail.css
  src/main/webapp/WEB-INF/views/meetup/img/meetup_detail_background.jpg
  src/main/webapp/WEB-INF/views/meetup/js/meetUpDetail.js
  src/main/webapp/WEB-INF/views/meetup/meetUpdetail.html
Labels: fix

#15 Fast/8 meetup detail modal create
  src/main/webapp/WEB-INF/views/meetup/asdasd2qwewq
  src/main/webapp/WEB-INF/views/meetup/css/meetUpDetail.css
  src/main/webapp/WEB-INF/views/meetup/js/meetUpDetail.js
  src/main/webapp/WEB-INF/views/meetup/meetUpdetail.html
Labels: feature

#17 [#7] 게시물 상세 조회 페이지 구현
  src/main/webapp/WEB-INF/views/common/common.css
  src/main/webapp/WEB-INF/views/common/common.js
  src/main/webapp/WEB-INF/views/common/footer.html
  src/main/webapp/WEB-INF/views/images/spring-logo.ico
  src/main/webapp/WEB-INF/views/main.css
  src/main/webapp/WEB-INF/views/main.html
  src/main/webapp/WEB-INF/views/main.js
  src/main/webapp/WEB-INF/views/meetup/css/postDetail.css
  src/main/webapp/WEB-INF/views/meetup/postDetail.html
Labels: feature

#18 [#10] 로그인,회원가입 폼 생성
  images/login_pet.png
  src/main/webapp/WEB-INF/views/images/login_pet.png
  src/main/webapp/WEB-INF/views/member/joinForm.html
  src/main/webapp/WEB-INF/views/member/loginForm.html
Labels: feature

#19 [#16] 마이페이지 뷰 구현 작업
  src/main/webapp/WEB-INF/views/common/header.html
  src/main/webapp/WEB-INF/views/meetup/css/meetUpDetail.css
  src/main/webapp/WEB-INF/views/meetup/js/meetUpDetail.js
  src/main/webapp/WEB-INF/views/meetup/meetUpdetail.html
  src/main/webapp/WEB-INF/views/member/css/joinForm.css
  src/main/webapp/WEB-INF/views/member/css/login.css
  src/main/webapp/WEB-INF/views/member/css/mypage.css
  src/main/webapp/WEB-INF/views/member/joinForm.html
  src/main/webapp/WEB-INF/views/member/js/mypage.js
  src/main/webapp/WEB-INF/views/member/loginForm.html
  src/main/webapp/WEB-INF/views/member/mypage.html
Labels: feature

#21 [#20] Spring 기본 패키지 생성
  src/main/java/com/kcc/springmini/domain/meetup/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MemberRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberRequestDto.java
  src/main/java/com/kcc/springmini/domain/member/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/domain/post/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/post/model/dto/MemberRequestDto.java
  src/main/java/com/kcc/springmini/domain/post/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/springmini/domain/post/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/post/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/post/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/post/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/post/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/post/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/MemberRequestDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/MemberServiceImpl.java
  src/main/java/com/kcc/springmini/global/aop/dummy
  src/main/java/com/kcc/springmini/global/config/dummy
  src/main/java/com/kcc/springmini/global/exception/dummy
  src/main/resources/mapper/dummy
Labels: setting, feature

#24 [#NoIssue] 기본 의존성 추가 및 클래스 명 변경
  pom.xml
  src/main/java/com/kcc/springmini/HelloController.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/dto/MeetUpResponseDto.java
  src/main/java/com/kcc/springmini/domain/meetup/model/vo/MeetUpVO.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepository.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/MeetUpRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/meetup/repository/mapper/MeetUpMapper.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpService.java
  src/main/java/com/kcc/springmini/domain/meetup/service/MeetUpServiceImpl.java
  src/main/java/com/kcc/springmini/domain/post/controller/PostController.java
  src/main/java/com/kcc/springmini/domain/post/model/dto/PostRequestDto.java
  src/main/java/com/kcc/springmini/domain/post/model/dto/PostResponseDto.java
  src/main/java/com/kcc/springmini/domain/post/model/vo/PostVO.java
  src/main/java/com/kcc/springmini/domain/post/repository/PostRepository.java
  src/main/java/com/kcc/springmini/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/post/repository/mapper/PostMapper.java
  src/main/java/com/kcc/springmini/domain/post/service/PostService.java
  src/main/java/com/kcc/springmini/domain/post/service/PostServiceImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleRequestDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/vo/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/application.yml
Labels: setting, refactor

#25 [#noissue] yml 세팅, data 추가
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: setting, feature

#30 [#29] 모임 등록 view 구현 작업
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/webapp/WEB-INF/views/meetup/meetupRegister.jsp
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/css/meetupRegister.css
Labels: feature

#31 [#noissue] jsp 파일 변경 (충돌 해결)
  pom.xml
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/Schedule.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/vo/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/data.sql
Labels: fix

#33 [#22] 모임일정 목록 조회 로직 구현
  pom.xml
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/Schedule.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/PageDto.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/mapper/ScheduleMapper.xml
Labels: setting, feature, refactor

#36 [#32] 회원가입 기능 구현
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/member/controller/MemberController.java
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepository.java
  src/main/java/com/kcc/springmini/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/member/repository/mapper/MemberMapper.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberService.java
  src/main/java/com/kcc/springmini/domain/member/service/MemberServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
  src/main/webapp/resources/common/header.jsp
  src/main/webapp/resources/js/joinForm.js
Labels: feature

#38 [#37] 모임생성 view 수정 작업
  src/main/java/com/kcc/springmini/domain/member/model/vo/MemberVO.java
  src/main/webapp/WEB-INF/views/meetup/meetupRegister.jsp
  src/main/webapp/WEB-INF/views/member/joinForm.jsp
  src/main/webapp/WEB-INF/views/member/loginForm.jsp
  src/main/webapp/resources/css/meetupRegister.css
  src/main/webapp/resources/js/joinForm.js
  src/main/webapp/resources/js/meetupRegister.js
Labels: refactor

#40 [#34] 모임 일정 목록 조회 로직 구현
  src/main/java/com/kcc/springmini/domain/common/model/PageRequestDto.java
  src/main/java/com/kcc/springmini/domain/meetup/controller/MeetUpController.java
  src/main/java/com/kcc/springmini/domain/schedule/controller/ScheduleController.java
  src/main/java/com/kcc/springmini/domain/schedule/model/ScheduleVO.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/PageResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/model/dto/ScheduleResponseDto.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/ScheduleRepositoryImpl.java
  src/main/java/com/kcc/springmini/domain/schedule/repository/mapper/ScheduleMapper.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleService.java
  src/main/java/com/kcc/springmini/domain/schedule/service/ScheduleServiceImpl.java
  src/main/java/com/kcc/springmini/global/exception/BadRequestException.java
  src/main/java/com/kcc/springmini/global/exception/ExceptionResponse.java
  src/main/java/com/kcc/springmini/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/springmini/global/exception/NotFoundException.java
  src/main/java/com/kcc/springmini/global/exception/dummy
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/ScheduleMapper.xml
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/meetup/meetupDetail.jsp
  src/main/webapp/resources/js/meetupDetail.js
Labels: feature, refactor
